# Setup project language
language: node_js
node_js:
  - node

# Whitelist branches
branches:
  only:
    - master

# Install & setup Google Cloud SDK
before_install:
  - openssl aes-256-cbc -K $encrypted_2a20bd2e68d5_key -iv $encrypted_2a20bd2e68d5_iv -in .google.credentials -out google.json -d
  - "gcloud auth activate-service-account --key-file google.json -q"
  - "gcloud config set project rokajdnik-com -q"

# Prepare deploy artifacts
script: "npm run build"

# Setup deploy
deploy:
  - provider: script
    skip_cleanup: true
    script: "gsutil -m rsync -d -r dist/ gs://eu-rokajdnik-com"
    on:
      branch: master
